name: Code Coverage

on:
  push:
    branches:
      - '**'

jobs:
  code-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run prebuild steps
        uses: ./.github/actions/prebuild

      - name: Run RSpec Tests
        run: bundle exec rspec

      - name: Measure Code Coverage
        run: bundle exec rspec --format documentation --format SimpleCov

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
