name: RSpec

on:
  push:
    branches:
      - '**'

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: timur
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2

      - name: Run prebuild steps
        uses: ./.github/actions/prebuild

      - name: Run RSpec Tests
        run: bundle exec rspec
