name: RSpec

on:
  push:
    branches:
      - '**'

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run prebuild steps
        uses: ./.github/actions/prebuild

      - name: Run RSpec Tests
        run: bundle exec rspec
